#ifndef JIEBA_LOGO_H
#define JIEBA_LOGO_H

#define JIEBA_VERSION "0.0.1"
#define JIEBA_EXT_AUTHOR "年嵩"
#define JIEBA_LOGO_BASE64 "/9j/2wCEAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAx " \
"NDQ0Hyc5PTgyPC4zNDIBCQkJDAsMGA0NGDIhHCEyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy" \
"MjIyMjIyMjIyMjIyMjIyMjIyMjIyMv/AABEIABQAFAMBIgACEQEDEQH/xAGiAAABBQEBAQEBAQAA" \
"AAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGh" \
"CCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hp" \
"anN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV" \
"1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQAC" \
"AQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXx" \
"FxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqS" \
"k5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T1" \
"9vf4+fr/2gAMAwEAAhEDEQA/ADxbc6lptjZHTXiiZ4ULySLu/gUgenPP5V12lXD3Phu0vZoI1uJr" \
"ZJHVF4DFQT/OsTU7H+29Zh0w3Jt0itIW3EZDOQqgY78kfSuZ8N65cadrU+mmVzbNiNcncqtjjGfX" \
"kflXPFtX7M5ZYhTqKmo7X1O0oqLzBSeYKZ0XPLbfxTq0Mbzx3LK+zyyQSMj8/wDOKl0W4a40a7uH" \
"C+Y1wrZHYgHGKwI/+PN/r/QVteH/APkXbj/rsP8A0E1lL4GTThH6y3bX/gHQ2viW9nt0kaODJHOF" \
"P+NTf2/d/wDPOH8j/jWBp/8Ax5R/SrVblH//2Q==" 
#define JIEBA_LOGO_DATA "data:image/png;base64," JIEBA_LOGO_BASE64
#define JIEBA_LOGO_IMG "<img src=\""JIEBA_LOGO_DATA"\" alt=\"logo\" />\n"

#endif
