jieba.lo: /home/niansong/Downloads/php-5.5.30/ext/jieba/jieba.cpp
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/home/niansong/Downloads/php-5.5.30/ext/jieba $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /home/niansong/Downloads/php-5.5.30/ext/jieba/jieba.cpp -o jieba.lo 
$(phplibdir)/jieba.la: ./jieba.la
	$(LIBTOOL) --mode=install cp ./jieba.la $(phplibdir)

./jieba.la: $(shared_objects_jieba) $(JIEBA_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_jieba) $(JIEBA_SHARED_LIBADD)

